# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kongctl < Formula
  desc "Developer CLI for Kong"
  homepage "https://github.com/kong/kongctl"
  version "0.0.11"

  on_macos do
    on_intel do
      url "https://github.com/Kong/kongctl/releases/download/v0.0.11/kongctl_darwin_amd64.zip"
      sha256 "4b35bad0617de000c61142a6d2c1657772387937213496bdcd523743306afb2c"

      def install
        bin.install "kongctl"
      end
    end
    on_arm do
      url "https://github.com/Kong/kongctl/releases/download/v0.0.11/kongctl_darwin_arm64.zip"
      sha256 "86c154d4a97f64bfdbcf47b7603446a8a2a5804079f7b63b20d44c6772e419b5"

      def install
        bin.install "kongctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Kong/kongctl/releases/download/v0.0.11/kongctl_linux_amd64.zip"
        sha256 "00306fdd1b4700e4cd8e62e66fce539ddc1ceb8ce2248d0ce86a211aa80a684f"

        def install
          bin.install "kongctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Kong/kongctl/releases/download/v0.0.11/kongctl_linux_arm64.zip"
        sha256 "f8a378510fa7e45dc8d4cb9c07e9befbb55598f870612a2270dbae01e3337ab1"

        def install
          bin.install "kongctl"
        end
      end
    end
  end

  test do
    system "#{bin}/kongctl", "version"
  end
end
