# This file was generated by GoReleaser. DO NOT EDIT.
cask "kongctl" do
  version "0.10.0"

  name "kongctl"
  desc "Developer CLI for Kong"
  homepage "https://github.com/kong/kongctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kongctl"

  on_macos do
    on_intel do
      sha256 "e3f694c1616483d95989819d1b9e267acfc17363312d8c4425174759e0b50787"
      url "https://github.com/Kong/kongctl/releases/download/v#{version}/kongctl_darwin_amd64.zip"
    end
    on_arm do
      sha256 "ff718308fc8904ae1824911b28a579196cc33fd7008ae4e6ff864c8d02effadc"
      url "https://github.com/Kong/kongctl/releases/download/v#{version}/kongctl_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "5ea812bb4858050fa979ac815c9a9abdebda52c1d423fff9abeac2432fb7aa64"
      url "https://github.com/Kong/kongctl/releases/download/v#{version}/kongctl_linux_amd64.zip"
    end
    on_arm do
      sha256 "6955e516137c674da91aaf986898f21b52627e3e24ffeebfa8bb53cd1c49ed93"
      url "https://github.com/Kong/kongctl/releases/download/v#{version}/kongctl_linux_arm64.zip"
    end
  end

  # No zap stanza required
end
