# This file was generated by GoReleaser. DO NOT EDIT.
cask "kongctl" do
  version "1.2.1"

  name "kongctl"
  desc "Developer CLI for Kong"
  homepage "https://github.com/kong/kongctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kongctl"

  on_macos do
    on_intel do
      sha256 "17ee5aa8ff9890477c8fa971ccf18cc29fb382186d5293af7992d5ffe6d84757"
      url "https://github.com/Kong/kongctl/releases/download/v#{version}/kongctl_darwin_amd64.zip"
    end
    on_arm do
      sha256 "b19ec501044f3bcb5193063cac2eaedc45578cf9cbe6642a3129447f2894aea7"
      url "https://github.com/Kong/kongctl/releases/download/v#{version}/kongctl_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "0c167fa347ee3f65cccf46377776c0a5b6d1599c9e9b2d202bdb9d14ec604340"
      url "https://github.com/Kong/kongctl/releases/download/v#{version}/kongctl_linux_amd64.zip"
    end
    on_arm do
      sha256 "00a63d4ba30fe595fdf8aa2d04b65819f8fbe38b525b710e9da18550efce3801"
      url "https://github.com/Kong/kongctl/releases/download/v#{version}/kongctl_linux_arm64.zip"
    end
  end

  # No zap stanza required
end
