# This file was generated by GoReleaser. DO NOT EDIT.
cask "kongctl" do
  version "1.9.0"

  on_macos do
    on_arm do
      sha256 "e4f77ecae205a8e4d30f3b97efe532f59da675baa614ee774650bca865f5b0f1"
      url "https://github.com/Kong/kongctl/releases/download/v#{version}/kongctl_darwin_arm64.zip"
    end
    on_intel do
      sha256 "54dec1a8134f6a7f77f006992766b65134dda8604d6fdf959a3e94b0468a5c6b"
      url "https://github.com/Kong/kongctl/releases/download/v#{version}/kongctl_darwin_amd64.zip"
    end
  end
  on_linux do
    on_arm do
      sha256 "bc5ae52d191e73aec8c210ec93b3b0085cec7e8e12a67e29eacb495e877118f2"
      url "https://github.com/Kong/kongctl/releases/download/v#{version}/kongctl_linux_arm64.zip"
    end
    on_intel do
      sha256 "f137d037fbf0c850a49a24bbe2296113d93625972bdef1473d79d018bd7c5515"
      url "https://github.com/Kong/kongctl/releases/download/v#{version}/kongctl_linux_amd64.zip"
    end
  end

  name "kongctl"
  desc "Developer CLI for Kong"
  homepage "https://github.com/kong/kongctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kongctl"

  # No zap stanza required
end
